# Automatically generated by jpa
CREATE TABLE attendance
(
    id       INT          NOT NULL
        PRIMARY KEY,
    appid    VARCHAR(255) NULL,
    extra    VARCHAR(255) NULL,
    face     VARCHAR(255) NULL,
    name     VARCHAR(255) NULL,
    nickname VARCHAR(255) NULL,
    plan     VARCHAR(255) NULL,
    tel      VARCHAR(255) NULL,
    uid      INT          NOT NULL
)
    ENGINE = MyISAM;

CREATE TABLE bless
(
    id         INT          NOT NULL
        PRIMARY KEY,
    avatar_url VARCHAR(255) NULL,
    city       VARCHAR(255) NULL,
    country    VARCHAR(255) NULL,
    gender     VARCHAR(255) NULL,
    language   VARCHAR(255) NULL,
    nick_name  VARCHAR(255) NULL,
    openid     VARCHAR(255) NULL,
    province   VARCHAR(255) NULL,
    time       VARCHAR(255) NULL,
    uid        INT          NOT NULL
)
    ENGINE = MyISAM;

CREATE TABLE comment
(
    id       INT          NOT NULL
        PRIMARY KEY,
    face     VARCHAR(255) NULL,
    nickname VARCHAR(255) NULL,
    time     VARCHAR(255) NULL,
    uid      INT          NOT NULL,
    words    VARCHAR(255) NULL
)
    ENGINE = MyISAM;

CREATE TABLE hibernate_sequence
(
    next_val BIGINT NULL
)
    ENGINE = MyISAM;

CREATE TABLE location
(
    id  INT    NOT NULL
        PRIMARY KEY,
    lat DOUBLE NOT NULL,
    lon DOUBLE NOT NULL,
    uid INT    NOT NULL
)
    ENGINE = MyISAM;

CREATE TABLE main_info
(
    id       INT          NOT NULL
        PRIMARY KEY,
    address  VARCHAR(255) NULL,
    app_name VARCHAR(255) NULL,
    appid    VARCHAR(255) NULL,
    code     VARCHAR(255) NULL,
    cover    VARCHAR(255) NULL,
    date     VARCHAR(255) NULL,
    he       VARCHAR(255) NULL,
    he_tel   VARCHAR(255) NULL,
    hotel    VARCHAR(255) NULL,
    lat      DOUBLE       NOT NULL,
    lng      DOUBLE       NOT NULL,
    lunar    VARCHAR(255) NULL,
    music    VARCHAR(255) NULL,
    qrimg    VARCHAR(255) NULL,
    share    VARCHAR(255) NULL,
    she      VARCHAR(255) NULL,
    she_tel  VARCHAR(255) NULL,
    thumb    VARCHAR(255) NULL,
    uid      INT          NOT NULL
)
    ENGINE = MyISAM;

CREATE TABLE photo
(
    id      INT          NOT NULL
        PRIMARY KEY,
    addtime VARCHAR(255) NULL,
    image   VARCHAR(255) NULL,
    uid     INT          NOT NULL
)
    ENGINE = MyISAM;

CREATE TABLE wx_user
(
    id         INT          NOT NULL
        PRIMARY KEY,
    avatar_url VARCHAR(255) NULL,
    city       VARCHAR(255) NULL,
    country    VARCHAR(255) NULL,
    gender     VARCHAR(255) NULL,
    language   VARCHAR(255) NULL,
    nick_name  VARCHAR(255) NULL,
    province   VARCHAR(255) NULL,
    uid        INT          NOT NULL
)
    ENGINE = MyISAM;

